[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PyAres"
dynamic = ["version"]
description = "The official Python library for ARES."
readme = "README.md"
requires-python = ">= 3.10"
license = { text = "MIT" }
authors = [{ name = "AFRL", email = "AFRL.RX.AREScontact@us.af.mil" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "ares-datamodel >= 0.31.0",
]

[project.urls]
Homepage = "https://github.com/AFRL-ARES/PyAres"

[tool.hatch.version]
source = "env"
variable = "PYARES_PACKAGE_VERSION"

[tool.hatch.build.targets.wheel]
packages = ["PyAres"]
